### ISSUE TITLE
HW2

### ISSUE THREAD

**Issue by gaboun** [gaboun/su-mt4007#2]

**Comment by BenjaminTillius** [comment]
- Has the person answered all the questions?
Yes all questions are answered in a good way.

- Is there something you really like about the report?
I like the structure, it is really easy to follow. Also both the choice to compare list vs sold price and the choice to do a plot of stroke compared by age where good and easy to understand choices. 

- Is anything unclear?
Not really. For some reason the "Swedish election 2018; Task 3" seem to show the top 5 municipialities instead of the top 3, but the code looks like it is correct (top 3).

**Comment by bettyfranklamanuens** [comment]
# Passed

Good job! Thank you for a nice report.
