### ISSUE TITLE
hw4 ready

### ISSUE THREAD

**Issue by gaboun** [gaboun/su-mt4007#4]

**Comment by AlvarMikkola** [comment]
I think you have answered all the questions and generated all the required plots. Your homework is overall easy to follow, but I would have liked to see a bit more documentation for certain parts of the code and a deeper explanation of the results, for example, the tables you plotted. This would have made the homework feel more like a report. Otherwise I think the homework was good and nothing was unclear. Great job!

**Comment by bettyfranklamanuens** [comment]
# Passed

Thank you for a very nice report!

## General

Your results are correct and you explain your steps clearly. You also handle the missing values in a good way, well done!
